### ISSUE TITLE
Updates incoming?

### ISSUE THREAD

**Issue by generalrandom** [Queeq/pydtc#1]
Hey, thanks for writing this software.

Are you planning on releasing any updates? I've made some small changes I could commit to the repo but I'm guessing you've already made the same changes.

If you like I can submit a pull request with what I've done.

**Comment by Queeq** [comment]
Hi,
Welcome, glad it's been useful to someone :)
I'm not doing any changes to the code, so feel free to submit pull requests.
Thanks!

**Comment by Queeq** [comment]
Have just fixed a couple of bugs revealed yesterday during internal usage

**Comment by michaelfresco** [comment]
this is really awesome, got it working on MacOs

**Comment by michaelfresco** [comment]
I'm trying to build a custom quoteboard that fits in the menubar of MacOs. So getting live quotes would be really nice. Is there a way to get the latest quotes from Sierra? not just historical data?

**Comment by Queeq** [comment]
No, live data is not supported. You could download historical data periodically (say, several times per minute). For crypto data, you may get the stream directly from exchanges using, for example, [cryptofeed](https://github.com/bmoscon/cryptofeed).

**Comment by michaelfresco** [comment]
That’s smart! I see that the str_to_tstamp function takes any format, so I could also specify a time frame of the last 5 mins. Very excited about all of this. Thanks!

**Comment by michaelfresco** [comment]
Hi queeq, I demo-ed your software in our local meetup. People loved it! https://www.youtube.com/watch?v=1NuIePM7ieY

**Comment by Queeq** [comment]
Welcome. Glad it was useful :)
