### ISSUE TITLE
using 'exchange' argument is not processed

### ISSUE THREAD

**Issue by eabase** [Queeq/pydtc#3]
It seem that the *dtc_download()* function argument **`exchange="anything"`** is not used? 
```
data = dtc_download('EURUSD', exchange='anyGarbageOk', start_date='2020.12.20', server=("0.0.0.0", 11098), debug=True)
```

**Comment by Queeq** [comment]
It is translated to Sierra Chart as is in the [HISTORICAL_PRICE_DATA_REQUEST](https://dtcprotocol.org/index.php?page=doc/DTCMessages_HistoricalPriceDataMessages.php#Messages-HISTORICAL_PRICE_DATA_REQUEST). It should be seen in the debug mode. I believe it is ignored by SC for some symbols.

**Comment by eabase** [comment]
> Optional: The exchange for the Symbol.
