### ISSUE TITLE
Update DTC to use v8

### ISSUE THREAD

**Issue by eabase** [Queeq/pydtc#4]
We need to update the DTC file `DTCProtocol_pb2.py` from version 7 to 8, as well.

Download latest files with:
```bash
#!/usr/bin/env bash
dfiles=(DTCProtocol.h DTCProtocol.cpp DTCProtocolVLS.h DTCProtocolVLS.cpp DTCProtocol.proto)
durl="https://dtcprotocol.org/DTC_Files/"
for f in "${dfiles[@]}"; do u="${durl}${f}"; echo -n "Downloading: ${u}"; curl -kLOs "${u}" && echo "  ok"; done;
echo "Done"
```

Then:
```bash
# Create a "new" DTCProtocol_pb2.py
protoc --python_out=. DTCProtocol.proto 
```

**Comment by VideoPac** [comment]
Hey,
I am also trying to make this work but I'm kind of a noob :)
I managed to generate the new DTCProtocol_pb2.py file generated from DTCProtocol.proto, but now when for example I run :

```
data = dtc_download(symbol="ESH21_FUT_CME",
                    exchange="Futures - CME",
                    start_date="01.01.2021",
                    server=("127.0.0.1", 11098),
                    debug=True)
```
and then :

`header = next(data)`

I get a:

```
Exception in thread MessageReceiver:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "<ipython-input-36-fea38fb5a1d3>", line 35, in run
  File "<ipython-input-36-fea38fb5a1d3>", line 64, in _get_message
  File "<ipython-input-32-290e995b4256>", line 43, in dtc_bin_decoder
struct.error: unpack requires a buffer of 4 bytes
```

Any idea what's wrong ?
Are you also using Sierra Chart ?

**Comment by Queeq** [comment]
Thanks for suggestion @eabase, I'll do it when I get some more time at hand.
@VideoPac and @eabase any particular reason to generate the new protocol file? My SierraChart (one of the last versions) works with the old one just fine.
Also, @VideoPac, I never tried it with ipython. Does it work for you as a standalone python script?

**Comment by VideoPac** [comment]
Hey @Queeq !
No, as a standalone I get the same error... But as I said I am a beginner and even if I'm trying for 2 days to make this work I still may do something stupidly wrong... Let me describe what I've done so far.
I'm on Windows 10, I have installed pydtc with a command prompt :

`pip install git+https://github.com/Queeq/pydtc`

it went to C:\Users\user\anaconda3\Lib\site-packages\pydtc
Then I have created a pydtc_mytest.py script in that folder which contains only :

```
import pandas as pd
from pydtc import dtc_download

data = dtc_download(symbol="ESH21_FUT_CME",
                                    exchange="Futures - CME",
                                    start_date="01.01.2021",
                                    server=("127.0.0.1", 11098),
                                    debug=True)

header = next(data)
```

When I run that script I get the aforementioned error no matter which DTCProtocol_pb2.py v7 or v8 I put in the pydtc\DTC folder.
In Sublime Text it shows like this :

```
Exception in thread MessageReceiver:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\user\anaconda3\lib\site-packages\pydtc\main.py", line 217, in run
    self._get_message()
  File "C:\Users\user\anaconda3\lib\site-packages\pydtc\main.py", line 246, in _get_message
    dtc_message = dtc_bin_decoder(dtc_message, msg_body)
  File "C:\Users\user\anaconda3\lib\site-packages\pydtc\main.py", line 135, in dtc_bin_decoder
    struct.unpack('<' + struct_fmt, bin_value)[0])  # little-endian
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by eabase** [comment]
@VideoPac 
Maybe post your issue as a separate issue.

@Queeq 
> any particular reason to generate the new protocol file?

Yes, there have been updates, and some other examples from the SC forums doesn't work. However, SC people doesn't seem to know exactly what's going on either, as there are no answers to my inquiries there while, finding unsupported items in the protocol files.

**Comment by eabase** [comment]
Hmm, very strange. 
It seem that [`MARKET_DEPTH_UPDATE_LEVEL_COMPACT`](https://www.sierrachart.com/index.php?page=doc/DTCMessages_MarketDataMessages.php#Messages-MARKET_DEPTH_UPDATE_LEVEL) is not available in v8. 

```bash
./old_DTCProtocol_pb2.py:189:      name='MARKET_DEPTH_UPDATE_LEVEL_COMPACT', index=34, number=118,
./old_DTCProtocol_pb2.py:1211:MARKET_DEPTH_UPDATE_LEVEL_COMPACT = 118
```

Hmm, yes, you're probably right. I need to read this again:

* https://www.sierrachart.com/index.php?page=doc/DTCProtocol.php
* https://www.sierrachart.com/index.php?page=doc/DTCProtocol.php#DTCFiles

Seem like it was removed from v8 for unknown reason: 
* https://dtcprotocol.org/DTC_Files/DTCProtocol.proto
*

**Comment by Queeq** [comment]
@eabase 
There are lots and lots changes indeed, but it seems reasonable to me to follow the progress. I'll bump it to v8.

@VideoPac 
It's indeed better to create a separate issue. So far I suspect it's because you use Anaconda Python, but I never used it and hence don't know what specifics it brings that could prevent standard library functions to fail. I could only advise to use plain Python 3.8 from here: https://www.python.org/downloads/windows/

**Comment by eabase** [comment]
@Queeq 
Yes, and some of the DTC files found in the SierraChart installation directory are different:
```
 297672 Dec 17 13:54 DTCProtocol.cpp
  56461 Dec 17 03:16 DTCProtocol_NonStandard.cpp
 100491 Dec 17 03:16 DTCProtocolVLS.cpp
 121059 Dec 17 13:54 DTCProtocol.h
  56941 Dec 17 03:16 DTCProtocol_NonStandard.h
  93071 Dec 17 03:16 DTCProtocolVLS.h
  45833 Dec 17 13:54 DTCProtocol.proto
```
Vs

```
272965 Dec 24 03:48 DTCProtocol.cpp
 93646 Dec 24 03:48 DTCProtocolVLS.cpp
111199 Dec 24 03:48 DTCProtocol.h
 85438 Dec 24 03:48 DTCProtocolVLS.h
   198 Dec 24 06:31 DTCprotocol.i
 41815 Dec 24 03:48 DTCProtocol.proto
496900 Dec 24 07:04 DTCProtocol_pb2.py      # v8
333429 Dec 24 09:37 old_DTCProtocol_pb2.py  # v7
```

This is really BS from the SC support perspective. There they tell you to use the ones from their download, but then they don't use those themselves, while sending us over for support at the DTC forum pages...

**Comment by eabase** [comment]
@VideoPac 
Try this instead: 
```
data = dtc_download('EURUSD', exchange='anyShitOk', start_date='2021.01.04', server=("0.0.0.0", 11098), debug=True)
```
