### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by VideoPac** [Queeq/pydtc#5]
Hey,

After trying to solve this by myself unsuccessfully for a few days, I post this issue in a separate thread as suggested by @Queeq.
I am on windows 10 with an Anaconda installation.
When I run :
```
data = dtc_download(symbol="ESH21_FUT_CME",
                    exchange="Futures - CME",
                    start_date="01.01.2021",
                    server=("127.0.0.1", 11098),
                    debug=True)
header = next(data)
```
 I get :
```
Exception in thread MessageReceiver:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "<ipython-input-18-fea38fb5a1d3>", line 35, in run
  File "<ipython-input-18-fea38fb5a1d3>", line 64, in _get_message
  File "<ipython-input-12-54cc7b59e7b0>", line 63, in dtc_bin_decoder
struct.error: unpack requires a buffer of 4 bytes
```

the error seems to come from
`setattr(dtc_message, f.name,  struct.unpack('<' + struct_fmt, bin_value)[0])  # little-endian`
at the end of dtc_bin_decoder()

@Queeq suggested to try the script with a pure Python installation (not Anaconda) but I'd really rather figure this out under Anaconda because that's what I will be using ultimately and debugging this also helps me understanding how the code work.

I am not sure this is relevant, but I have noticed that when I run a simple :
```
variable = struct.pack('iii', 1, 2, 3)
print(variable)
```

I get :
`b'\x05\x00\n\x00\x0f\x00\x00\x00'`

Where people seems to get :
`b'\x05\x00\n\x00\x00\x00\x00\x00\x0f\x00\x00\x00f\x00\x00\x00\x00'`

Please help :)

**Comment by Queeq** [comment]
Strange, with `struct.pack('iii', 1, 2, 3)` I get `b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'`

Overall, I don't think I could help here as this is something in Python standard library. I tried to run debug and see what're the arguments of the `unpack` when it's first called in this line, and it is this: `struct.unpack('<i', b'\x08\x00\x00\x00')`. It gives me `(8,)` as a result (this is protocol version I believe). If `struct.unpack()` gives you something different I'd advise you to open an issue with Anaconda instead.

**Comment by VideoPac** [comment]
@Queeq Ok thanks, I am doing that

**Comment by eabase** [comment]
@VideoPac 
1. Maybe this is a character set issue? Because your response is half the lengths of ours. I use UTF-8 as default on Windows.
2. Did you try using a European style date? -- `yyyy-mm-dd`
3. Are you using 64-bit anaconda?
